### ISSUE TITLE
Support IAsyncDisposable

### ISSUE THREAD

**Issue by xsoheilalizadeh** [solidtoken/SpecFlow.DependencyInjection#48]
If you register a class that implements `IAsyncDisposable` to the container it would throw following exception:

```c#
TearDown : System.InvalidOperationException : 'IntegrationTests.Order' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
--TearDown
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.Dispose()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Dispose()
   at BoDi.ObjectContainer.Dispose()
   at TechTalk.SpecFlow.Infrastructure.ContextManager.InternalContextManager`1.DisposeInstance()
   at TechTalk.SpecFlow.Infrastructure.ContextManager.InternalContextManager`1.Cleanup()
   at TechTalk.SpecFlow.Infrastructure.ContextManager.CleanupScenarioContext()
   at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnScenarioEnd()
   at TechTalk.SpecFlow.TestRunner.OnScenarioEnd()
   at GT.Buzzinga.Tests.IntegrationTests.Features.SeedGenerationFeature.TestTearDown()
```

Package version: 3.7.0 / .NET 5

cc @mbhoek

**Comment by xsoheilalizadeh** [comment]
I think it's related to BoDi package, if you confirm I can forward it to their repo.

**Comment by mbhoek** [comment]
@xsoheilalizadeh I think you are correct assuming that it's related to the BoDi package. It does not appear to call `DisposeAsync`. I did find a PR on SpecFlow trying to solve this (https://github.com/SpecFlowOSS/SpecFlow/pull/1614) but it does not seem ready to merge yet.

**Comment by mbhoek** [comment]
Update: although the PR mentioned above has been merged for the v4 release, the cause of this issue (BoDi) has not been fixed yet -- there is a PR for it however, so I'll be watching that (https://github.com/SpecFlowOSS/BoDi/pull/51).

**Comment by mbhoek** [comment]
Closing this issue because [the plugin will be donated to Reqnroll](https://github.com/solidtoken/SpecFlow.DependencyInjection/issues/106).
